version: '3'
services:
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      SECRET_KEY_BASE: 130ccf8f568227b0df63ab55f4ca1162fa779ae25b2cf0ed681c5c263086ad61b5add44ec01e91f0091fb930019507ae931c559f47bb31c4b16640e939a64fb4
      

      # config database
      # config routes --> root
